version: "3.7"
services:
  go-project:
    build: .

  go-project-dev:
    image: "golang:1.14"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./.go:/go
      - ./.go/cache/:/root/.cache/go-build
    command: ["sh", "-c", "/app/_scripts/dev.sh"]


  go-project-run:
    image: "golang:1.14"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./.go:/go
      - ./.go/cache/:/root/.cache/go-build
    command: ["sh", "-c", "/app/_scripts/run.sh"]

  go-project-install:
    image: "golang:1.14"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./.go:/go
      - ./.go/cache/:/root/.cache/go-build
    command: ["sh", "-c", "/app/_scripts/install.sh"]

