version: "3.6"
services:
    node-typescript:
        build: .
        image: "node-typescript"

    node-typescript-dev:
        image: "node:14.2-alpine"
        stdin_open: true
        tty: true
        volumes:
            - .:/app
        command: ["sh", "-c", "cd /app && yarn install && yarn dev-watch"]

    node-typescript-dev-debug:
        image: "node:14.2-alpine"
        stdin_open: true
        tty: true
        volumes:
            - .:/app
        command: ["sh", "-c", "cd /app && yarn install && yarn dev-debug"]
